-- Схема БД для бота «калькулятор долгов»
-- Применить: Supabase → SQL Editor → New query → вставить целиком → Run.
--
-- Бот работает через REST (PostgREST) с ключом service_role, поэтому RLS включён
-- и политик нет: обычные ключи (anon/authenticated) доступа не получат,
-- читать и писать может только бот.

create table if not exists public.debts (
    id         bigint generated by default as identity primary key,
    chat_id    bigint        not null,
    from_name  text          not null,
    to_name    text          not null,
    currency   text          not null default 'BYN',
    amount     numeric(14, 2) not null check (amount > 0),
    raw_text   text,
    created_at timestamptz   not null default now()
);

comment on table public.debts is
    'Долги: who (from_name) должен whom (to_name) сумму amount в валюте currency';
comment on column public.debts.chat_id is 'Telegram chat_id — долги разделены по чатам';
comment on column public.debts.raw_text is 'Исходное сообщение пользователя';

create index if not exists debts_chat_created_idx
    on public.debts (chat_id, created_at);
create index if not exists debts_pairs_idx
    on public.debts (chat_id, from_name, to_name, currency);

-- Тип записи: долг, возврат («Леша вернул Диме 3 рубля») или доля общего счёта
-- («Дима заплатил 10 за всех» — сумма делится между участниками).
-- Возврат уменьшает сальдо: from_name вернул to_name сумму amount.
alter table public.debts add column if not exists kind text not null default 'debt';
-- Ограничение пересоздаём: при первом применении схемы оно было только на debt/repayment.
alter table public.debts drop constraint if exists debts_kind_check;
alter table public.debts add constraint debts_kind_check
    check (kind in ('debt', 'repayment', 'expense'));

comment on column public.debts.kind is
    'debt — долг, repayment — возврат, expense — доля общего счёта (кто-то заплатил за всех)';

-- Привязка записей к пользователям Telegram: если бот узнал человека в списке участников
-- чата, долг хранится на его user id, а не только на имя (тогда «Лешак» и «Леша» — одно лицо).
alter table public.debts add column if not exists from_user_id bigint;
alter table public.debts add column if not exists to_user_id   bigint;
comment on column public.debts.from_user_id is 'Telegram user id должника/плательщика (если узнан)';
comment on column public.debts.to_user_id   is 'Telegram user id кредитора/получателя (если узнан)';

create index if not exists debts_users_idx
    on public.debts (chat_id, from_user_id, to_user_id);

-- Общий счёт («Дима заплатил 10 за всех») — одна операция из нескольких строк-долей:
-- у всех долей одной оплаты одинаковый group_id. По нему видно оригинал сообщения,
-- и /undo убирает весь счёт целиком, а не одну строку.
alter table public.debts add column if not exists group_id text;
comment on column public.debts.group_id is
    'Идентификатор общего счёта: одинаковый у всех долей одной оплаты (для /undo)';

create index if not exists debts_group_idx
    on public.debts (chat_id, group_id);

-- Участники чата: бот запоминает авторов сообщений, чтобы понимать, кто такой «Лешак»,
-- и сопоставлять имена из сообщений с реальными пользователями (@ники и id).
create table if not exists public.chat_members (
    chat_id      bigint      not null,
    user_id      bigint      not null,
    username     text,
    display_name text        not null default '',
    aliases      text[]      not null default '{}',
    last_seen    timestamptz not null default now(),
    primary key (chat_id, user_id)
);

comment on table public.chat_members is
    'Участники чата: id, @ник, имя и алиасы — по ним долги привязываются к пользователям';
comment on column public.chat_members.aliases is
    'Как ещё зовут человека в чате: «Леша», «Лёха» — подсказка для сопоставления имён';

-- Регистрация (/reg): человек сам связывает себя с именами, по которым его узнают.
-- Записи (долги, возвраты, общие счета) ведутся только на зарегистрированных.
alter table public.chat_members add column if not exists is_registered boolean not null default false;
comment on column public.chat_members.is_registered is
    'true — человек выполнил /reg: только на таких участников бот записывает долги';

create index if not exists chat_members_chat_idx
    on public.chat_members (chat_id);

alter table public.chat_members enable row level security;

create table if not exists public.bot_settings (
    chat_id          bigint      not null primary key,
    default_currency text        not null default 'BYN',
    updated_at       timestamptz not null default now()
);

comment on table public.bot_settings is
    'Настройки чата: валюта по умолчанию и признак того, что чат подтвердил пароль';

-- Пароль чата (CHAT_PASSWORD): бот работает только там, где он введён верно.
-- Сбрасывается, когда бота удаляют из чата, — при повторном добавлении спросим снова.
alter table public.bot_settings add column if not exists is_authorized boolean not null default false;
comment on column public.bot_settings.is_authorized is
    'true — чат подтвердил пароль, бот в нём работает';

-- Курсы валют (allratestoday): сколько базовой валюты стоит 1 единица валюты на дату.
-- Обновляются раз в день — при первом за сутки обращении к /d или /rates (без cron).
create table if not exists public.currency_rates (
    rate_date  date          not null,
    base       text          not null default 'BYN',
    currency   text          not null,
    rate       numeric(20, 8) not null check (rate > 0),
    source     text,
    updated_at timestamptz   not null default now(),
    primary key (rate_date, base, currency)
);

comment on table public.currency_rates is
    'Курсы валют по дням: rate = сколько base стоит 1 единица currency (1 USD = 3.25 BYN)';
comment on column public.currency_rates.base is
    'Базовая валюта, к которой приведён курс (RATES_BASE, по умолчанию BYN)';
comment on column public.currency_rates.source is
    'Источник курса: allratestoday (например wise / nbrb)';

create index if not exists currency_rates_lookup_idx
    on public.currency_rates (base, rate_date desc);

alter table public.currency_rates enable row level security;

create or replace function public.touch_bot_settings()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists bot_settings_touch on public.bot_settings;
create trigger bot_settings_touch
    before update on public.bot_settings
    for each row execute function public.touch_bot_settings();

alter table public.debts enable row level security;
alter table public.bot_settings enable row level security;

-- Состояние бота: смещение обработанных апдейтов Telegram — чтобы повторная доставка
-- (перезапуск, повтор вебхука) не записала один и тот же долг дважды
create table if not exists public.bot_state (
    key        text        not null primary key,
    value      text        not null,
    updated_at timestamptz not null default now()
);

comment on table public.bot_state is
    'Служебное состояние бота: например last_update_id — последний обработанный апдейт Telegram';

alter table public.bot_state enable row level security;

-- Проверка: должно вернуть 0 строк и не выдать ошибку.
select 'debts' as table_name, count(*) as rows from public.debts
union all
select 'bot_settings', count(*) from public.bot_settings
union all
select 'bot_state', count(*) from public.bot_state
union all
select 'chat_members', count(*) from public.chat_members
union all
select 'currency_rates', count(*) from public.currency_rates;
