-- Схема БД для бота «калькулятор долгов»
-- Применить: Supabase → SQL Editor → New query → вставить целиком → Run.
--
-- Бот работает через REST (PostgREST) с ключом service_role, поэтому RLS включён
-- и политик нет: обычные ключи (anon/authenticated) доступа не получат,
-- читать и писать может только бот.

create table if not exists public.debts (
    id         bigint generated by default as identity primary key,
    chat_id    bigint        not null,
    from_name  text          not null,
    to_name    text          not null,
    currency   text          not null default 'BYN',
    amount     numeric(14, 2) not null check (amount > 0),
    raw_text   text,
    created_at timestamptz   not null default now()
);

comment on table public.debts is
    'Долги: who (from_name) должен whom (to_name) сумму amount в валюте currency';
comment on column public.debts.chat_id is 'Telegram chat_id — долги разделены по чатам';
comment on column public.debts.raw_text is 'Исходное сообщение пользователя';

create index if not exists debts_chat_created_idx
    on public.debts (chat_id, created_at);
create index if not exists debts_pairs_idx
    on public.debts (chat_id, from_name, to_name, currency);

create table if not exists public.bot_settings (
    chat_id          bigint      not null primary key,
    default_currency text        not null default 'BYN',
    updated_at       timestamptz not null default now()
);

comment on table public.bot_settings is
    'Настройки чата: валюта по умолчанию, если в сообщении валюта не указана';

create or replace function public.touch_bot_settings()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists bot_settings_touch on public.bot_settings;
create trigger bot_settings_touch
    before update on public.bot_settings
    for each row execute function public.touch_bot_settings();

alter table public.debts enable row level security;
alter table public.bot_settings enable row level security;

-- Состояние бота: смещение обработанных апдейтов Telegram (нужно для режима GitHub Actions)
create table if not exists public.bot_state (
    key        text        not null primary key,
    value      text        not null,
    updated_at timestamptz not null default now()
);

comment on table public.bot_state is
    'Служебное состояние бота: например last_update_id — последний обработанный апдейт Telegram';

alter table public.bot_state enable row level security;

-- Проверка: должно вернуть 0 строк и не выдать ошибку.
select 'debts' as table_name, count(*) as rows from public.debts
union all
select 'bot_settings', count(*) from public.bot_settings
union all
select 'bot_state', count(*) from public.bot_state;
